export const SAVE_HOMEDATA = 'save_homedata'
export const SAVE_NAVDATA = 'save_navdata'
export const SAVE_CATELISTDATA = 'save_catelistdata'
export const SAVE_CATENAVDATA = 'save_catenavdata'
export const SAVE_SEARCHDATA = 'save_searchdata'
